### PR TITLE
added the 10k limit and a message when the user reaches it

### PR DESCRIPTION
**Pull request by AndersonCeci**
# Issue #270 
<hr>
## Solution 

ezgif-3-474959f91c

_The 10-character limit was added for testing puropses_
<hr>
### What needs to be done in this pr

- [ ] - When composing a text, if the user hits the character limit and continues typing, the cursor loops back to the beginning, overwriting existing text. (this needs to be fixed)
- [x] - When you approach the character limit and have to replace text, sometimes overlapping can result in a less smooth transition that doesn't look aesthetically pleasing. (as you can see on the video)
- [x] The limit message should be automatically removed Once the user reaches the character limit and deletes the text. (as seen below on the image)
Screenshot from 2023-09-29 00-41-40

- [ ] Cypress Tests

### CODE REVIEW

**Comment by AndersonCeci** [comment]
Hey @vaqueraoscar0 , FYI this is what I had in mind, let me know if you'll have any additional ideas on how I can improve it

**Comment by vaqueraoscar0** [comment]
@AndersonCeci Yes, that look better! The other thing that you might need to consider is regarding the editor’s box size, as the character count increases, the box also increases. Is the User expected to scroll down and notice the character limit message or should the screen be auto scrolled to the bottom to get the user to notice.

**Comment by AndiBraimllari** [comment]
> @AndersonCeci Yes, that look better! The other thing that you might need to consider is regarding the editor’s box size, as the character count increases, the box also increases. Is the User expected to scroll down and notice the character limit message or should the screen be auto scrolled to the bottom to get the user to notice.

Yea great point, based on the current implementation I'd also love to see an automatic scroll to the bottom so the user will be notified properly.

Let's see what @AndersonCeci thinks about this.

**Comment by AndersonCeci** [comment]
@AndiBraimllari , @vaqueraoscar0 I was initially considering making it sticky, but I believe auto-scrolling seems like a better idea.

**Comment by AndersonCeci** [comment]
[Screencast from 30.9.23 12:21:01.PD CEST.webm](https://github.com/OpenCovenant/quill/assets/37506005/6ef735b9-e900-424b-a010-03b926e8db1c)

These are the changes I made @AndiBraimllari , @vaqueraoscar0 

- I made the auto scroll (which needs to be fixed to stick to the bottom even when you delete text)
- And now the overlapping is fixed and the text is responsive when we delete text

**Comment by AndiBraimllari** [comment]
Looks pretty good to me! Well done. We can further refine this in the future.
Do you think you would you be able to add some Cypress tests to this?

**Pull request merged**
