### PR TITLE
Edit header.component.css: Add text-shadow on penda-header-logo when onhover

### PR DESCRIPTION
**Pull request by Tonykimanthi**
Since transitioning `font-weight` is nearly impossible in css, I instead used `text-shadow` to give that font-weight effect.
Feel free to customize it to your needs. Let me know if you need any further assistance, I will be happy to help.

### CODE REVIEW

**Comment by AndiBraimllari** [comment]
Hey, thanks for the nice PR!
Code looks great! I tried out some things and I really like how it looks if transition goes from `.5s` to `.4s`, and `+/-0.4px` to `+/-0.3px`, and finally a letter spacing of `0.01em`. I think this configuration creates a nice and subtle flow. If that's fine with you please push these changes and I'll deploy and merge them soon :)

**Comment by Tonykimanthi** [comment]
Let me know if you need further assistant. I'll be more than ready to help and collaborate to your future projects.🚀

**Comment by AndiBraimllari** [comment]
Hey, thanks for offering! If you'd like you can have a look at #396, #411 or #422. I'm not certain if your strengths lie in styling or scripting, but maybe one of these can be interesting for you :)
Let me know if you'll have any questions about them.

I'll merge this PR and make the suggested modifications in a follow-up PR, thanks again!

**Comment by AndiBraimllari** [comment]
Oh and if you'd like you can create a PR to add yourself to the list of contributors in the README :)

**Comment by Tonykimanthi** [comment]
> Hey, thanks for offering! If you'd like you can have a look at #396, #411 or #422. I'm not certain if your strengths lie in styling or scripting, but maybe one of these can be interesting for you :) Let me know if you'll have any questions about them.
> 
> I'll merge this PR and make the suggested modifications in a follow-up PR, thanks again!

Ok, I will look at them.

**Comment by Tonykimanthi** [comment]
> Oh and if you'd like you can create a PR to add yourself to the list of contributors in the README :)

Oh, I'll do it now🙂

**Pull request merged**
