### PR TITLE
Information icon issue

### PR DESCRIPTION
**Pull request by vaqueraoscar0**
## Information Icon Issue #314 
Seperated the two items to always be in opposite directions information description on the left, icon on the right.

## Image

Screenshot 2023-10-09 at 4 05 40 PM

### CODE REVIEW

**Comment by AndiBraimllari** [comment]
Looks great to me, simply please drop the code from #281 (which should also resolve the conflicts)

**Comment by vaqueraoscar0** [comment]
> Looks great to me, simply please drop the code from #281 (which should also resolve the conflicts)

Yup already did.

**Comment by AndiBraimllari** [comment]
Hmm it shows 15 files changed... Can you try syncing the main branch of your fork with the main of this repository, and then create a branch from that, and add those changes there, then create a PR from that branch? It is difficult to know what exactly has changed in this PR, and the only commits here should be the ones related to #314.
Let me know if you'll need help with this :)

**Comment by vaqueraoscar0** [comment]
so was the first PR what you wanted? Sorry i got confused when you said to "drop the code from https://github.com/OpenCovenant/quill/pull/281 (which should also resolve the conflicts)"

**Comment by AndiBraimllari** [comment]
Out of the commits present in this PR, I think the only relevant one is ca1d107 (information icon aligned to the right). This is the only commit that should be present here. You can create a new PR as I described (or you can force push, or in any other way you're comfortable with).

The initial commits are from the PR #281, which shouldn't be here, as every PR should only contain commits relevant to its scope (I guess you created the vaqueraoscar0:information-icon-issue branch from the vaqueraoscar0:issue-text-marking branch, but it should've been from the main of your fork).

Hopefully it is a bit clearer now, let me know if not.

**Pull request closed without merging**
