### PR TITLE
Improve code

### PR DESCRIPTION
**Pull request by AndiBraimllari**
Improve the implementation of two methods, also include some general improvements.

Can you double check the changes for `deleteTextMarking` and `storeWrittenText` @stackoversnow?

(should be merged after #94)

### CODE REVIEW

**Review by stackoversnow — COMMENTED** [review]
Includes lot of changes somehow already touched in #94 and #96 .
I will take a look after merge conflicts resolved.

**Comment by AndiBraimllari** [comment]
Conflicts resolved and the diff should now show only the actual changes added to this branch

**Comment by AndiBraimllari** [comment]
Another change that caused a bug in live is the check for `!textMarking.paragraph`, given that this returns indices for the paragraph that it belongs to, then the markings for the first paragraph would show only an empty string as returned by `getTextOfTextMarking`.

**Review by stackoversnow — APPROVED** [review]
Code looks good 👍

**Pull request merged**
