### PR TITLE
 CSS Nesting

### PR DESCRIPTION
**Pull request by Kledis98**
There are some things that need some discussion in order to make the code more understandable and cleaner.
1 - Maybe it does not look too well nesting more than 5 levels.
2- CSS nesting might look better if other CSS styles will be grouped together, because some CSS styles are way too spread.
Let me know what you think @AndiBraimllari  and I will continue the work.

### CODE REVIEW

**Comment by AndiBraimllari** [comment]
- In how many cases does it exceed 5 levels?
- What exactly are you referring to with CSS styles, and how would you like to group them?

Nice PR btw.

**Comment by Kledis98** [comment]
Until now, the max level I have used is 3, line 127-164.
What do you think about it ? 
Does it look good ? 

I was thinking like putting them in order, related to the HTML file itself. 
I will continue with it.

**Comment by AndiBraimllari** [comment]
Seems fine to me.

Ah you mean the order of CSS elements to match the order in which these elements appear in HTML? Sounds great!

**Comment by Kledis98** [comment]
Check the previous commit  when you have time. Let me know for anything.

**Comment by AndiBraimllari** [comment]
Looks good from what I can tell, please apply this to the rest of the stylings

**Comment by Kledis98** [comment]
Done the stylings on settings. I do really like the way that they are displayed there.

**Comment by AndiBraimllari** [comment]
Think having the styling displayed in a similar hierarchy in respect to the template is much easier to read and work with. Do you plan to make more changes here?

If not, please test things as much as you can so then we can merge it.

**Comment by Kledis98** [comment]
I will check them again and will let you know.

**Pull request merged**
