### PR TITLE
fixed suggestions css

### PR DESCRIPTION
**Pull request by Jeongseulho**
- Related issue : [#372](https://github.com/OpenCovenant/quill/issues/372)
- Change
  - add property `align-items: center;` at `.suggestions` tag
  - add property `margin-bottom: 0rem;` at `.suggestions-header` tag

image

### CODE REVIEW

**Comment by AndiBraimllari** [comment]
Nice work!
From what I can tell, the lines 445 and 449 are duplicated by mistake, can you confirm @AndersonCeci? If so, feel free to remove one of them @Jeongseulho. Also, do we need `rem` when specifying 0 here?
If you'd like you can also have a look at https://github.com/OpenCovenant/quill/issues/325 and/or https://github.com/OpenCovenant/quill/issues/312.
And finally, if you'd like, you can add your name in the list of contributors, see README.

**Comment by AndersonCeci** [comment]
> Nice work! From what I can tell, the lines 445 and 449 are duplicated by mistake, can you confirm @AndersonCeci? If so, feel free to remove one of them @Jeongseulho. Also, do we need `rem` when specifying 0 here? If you'd like you can also have a look at #325 and/or #312. And finally, if you'd like, you can add your name in the list of contributors, see README.

Upon reviewing one of my branches, I noticed duplicate merges. Removing one won't break anything.

**Comment by Jeongseulho** [comment]
- Duplication of lines 445 and 449:
I have noticed the duplication in lines 445 and 449, but I didn't remove the duplication due to a lack of understanding of the potential side effects it might have on the project. If you permit, I will remove this duplication.

- 0rem:
Additionally, although 'rem' is unnecessary, I noticed that the unit 'rem' is used throughout the CSS. For the sake of consistency, I specified it as 0rem. I will change this to 0.

- Regarding issues #325 and #312:
If I am allowed, I would gladly resolve these issues as well.

- Contributors:
If possible, I would be delighted to add my name as well. Thank you.

**Comment by AndiBraimllari** [comment]
Hey, yes to all of your points :D Feel free to do so. Let me know once you're done so I can merge this PR since it contains very few changes.

**Comment by Jeongseulho** [comment]
It's done!
- Change
    - fix property 0rem to 0
    - add contributor Jeongseulho at READEME.md

**Comment by AndiBraimllari** [comment]
Awesome, thanks for working on this! By the way, if you notice any minor code improvements (e.g. duplicated code like the CSS here, feel free to create an issue, and we can discuss it).
You should see your changes in deployment in less than 10 minutes.
Merging...

**Pull request merged**
