### PR TITLE
avoid double marking on paste

### PR DESCRIPTION
**Pull request by AndiBraimllari**

### CODE REVIEW

**Comment by AndiBraimllari** [comment]
When pasting text in the editor, the text is marked twice, the changes proposed in this PR avoid the second marking in this scenario.

**Comment by AndiBraimllari** [comment]
Wanna write some Cypress tests for this @AndersonCeci?

**Comment by AndiBraimllari** [comment]
It seems that the text is marked also when copied, which doesn't make much sense. Added code to account for this case as well.

**Comment by AndersonCeci** [comment]
> Wanna write some Cypress tests for this @AndersonCeci?

Sure, on it

**Comment by AndiBraimllari** [comment]
Skipping Cypress tests for now

**Pull request merged**
